name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@dev

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: marwie/wiki-test
        TARGET_BRANCH: main
        BUILD_SCRIPT: cd docs && yarn && yarn build
        BUILD_DIR: src/.vuepress/dist
